myboard/board/urls.py
from django.urls import path

from.import views

app_name = 'board'

urlpatterns = [
    # board/라면
    path('', views.index, name='index'),
    # 글읽기 주소 /board/0
    path('<int:id>/', views.read, name='detail'),
    # 글쓰기 주소
    path('write/', views.write, name='write'),
    # 수정 주소
    path('<int:id>/update/', views.update, name='update'),
    # 삭제 주소
    path('<int:id>/delete/', views.delete, name='delete'),
    # 댓글 쓰기 주소
    path('<int:id>/write_reply/', views.write_reply, name='write_reply'),
    # 댓글 삭제 주소(id:글번호, rid:댓글번호)
    path('<int:id>/delete_reply/<int:rid>/', views.delete_reply, name='delete_reply'),
    # 댓글 수정
    path('<int:id>/update_reply/', views.update_reply, name='update_reply'),


    # Ajax
    path('callAjax/', views.call_ajax),
    # ajax 댓글 목록
    path('load_reply/', views.load_reply),
    

]

myboard/myboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('common.urls')),
    path("admin/", admin.site.urls),
    path('board/', include('board.urls')),
    
]

myboard/board/models.py
from django.db import models
from django.utils import timezone  # 시간 정보에 관한 모듈

# auth_user 테이블과 매핑되는 모델
from django.contrib.auth.models import User

# Create your models here.

class Board(models.Model):
    # 번호는 pk설정 안하면 장고가 자동으로 id부여해줌
    #### 필드와 필드 사이에 ','금지 ####
    title = models.CharField(max_length= 100)  # 제목
    content = models.TextField(null=False, blank=False)  # 내용
    # writer = models.CharField(max_length=10)  # 작성자
    input_date = models.DateTimeField(default=timezone.now)  # 작성일
    view_count = models.IntegerField(default=0)  # 조회수
    # db에는 필드이름_기본키 로 열이 생성됨
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # java의 toString이랑 비슷하게
    # 객체 정보를 문자열로 돌려줌
    def __str__(self):
        return f'{self.id}: {self.title}'
    


class Reply(models.Model):
    # pk 자동 생성(id)
    # 게시글번호(fk)
    board_obj = models.ForeignKey(Board, on_delete=models.CASCADE)
    # 사용자(fk)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # 댓글 내용
    reply_content = models.TextField(blank=False, null=False)
    # 작성시간
    input_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.reply_content

myboard/board/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from django.core import serializers
from json import loads
from .models import Board, Reply
# Create your views here.

# 게시판 목록보기
def index(request):
    print('index() 실행 ')

    # 반환되는 queryset에 대해서 order_by함수 이용하면 특정 필드 기준으로 정렬
    # order_by에 들어가는 필드 이름 앞에 -를 붙이면 내림차순(DESC) 아니면 오름차순(ASC)
    result = None # 필터링된 리스트
    context = {}

    # request.GET : get방식으로 보낸 데이터들을 딕셔너리 타입으로 저장
    # print(request.GET)

    # 검색 조건과 검색 키워드가 있어야 필터링 실행
    if 'searchType' in request.GET and 'searchWord' in request.GET:
        search_type = request.GET['searchType'] # GET안의 문자열은
        search_word = request.GET['searchWord'] # html의 name 속성

        print('search_type: {}, search_word: {}'.format(search_type,search_word))

        # match: java switch랑 비슷
        match search_type:
            case 'title': # 검색기준이 제목일 때
                result = Board.objects.filter(title__contains = search_word)
            case 'writer': # 검색기준이 글쓴이일 때
                result = Board.objects.filter(writer__contains = search_word)
            case 'content': # 검색기준이 내용일 때
                result = Board.objects.filter(content__contains = search_word)

        # 검색을 했을때만 검색 기준과 키워드를 context에 넣는다
        context['searchType'] = search_type
        context['searchWord'] = search_word
    else : #QueryDict에 검색조건과 키워드가 없을 때
        result = Board.objects.all()

    # 검색 결과 또는 전체 목록을 id의 내림차순 정렬
    result = result.order_by('-id')

    # 페이징 넣기
    # Paginator(목록, 목록에 보여줄 개수)
    paginator = Paginator(result, 10)

    # Paginator 클래스를 이용해서 자른 목록의 단위에서
    # 몇 번째 단위를 보여줄 것인지 정한다
    page_obj = paginator.get_page(request.GET.get('page'))

    # context['board_list'] = result
    # 페이징한 일부 목록을 반환
    context['page_obj'] = page_obj

    return render(request, 'board/index.html', context)

def read(request, id):
    print('id=', id)

    board = Board.objects.get(id = id)

    # 고전적인 방법으로 댓글 가져오기
    # reply_list = Reply.objects.filter(board_obj = id).order_by('-id')

    # 조회수
    board.view_count = board.view_count + 1
    board.save()

    context = {
        'board':board,
        # 'replyList':reply_list
    }

    return render(request, 'board/read.html', context)


def home(request):
    return HttpResponseRedirect('/board/')

# 내가 따로 만든 로그인url이 있다면
# 넘겨야 한다
@login_required(login_url='common:login')
def write(request):

    if request.method == 'GET':  # 요청 방식이 GET이면 화면 표시
        return render(request, 'board/board_form.html')

    else:  # 요청 방식이 POST면
        # DB저장
        title = request.POST['title']
        content = request.POST['content']
        author = request.user #요청에 들어있는 User 객체


        # 객체.save()
        # board = Board(
        #     title = title,
        #     writer = writer,
        #     content = content
        # )
        # board.save()

        # 모델.object.create(값)
        Board.objects.create(
            title = title,
            author = author,  # 유저 객체 저장
            content = content
        )
        return HttpResponseRedirect('/board/')

@login_required(login_url='common:login')
def update(request, id):

    board = Board.objects.get(id = id)

    # 글쓴이와 현재 접속한 사용자의 username이 다르면 목록으로
    if board.author.username != request.user.username:
        return HttpResponseRedirect('/board/')

    if request.method == 'GET':
        context = {'board': board }
        return render(request, 'board/board_update.html', context)
    else:
        board.title = request.POST['title']
        board.content = request.POST['content']
        board.save()
    return HttpResponseRedirect('/board/')

@login_required(login_url='common:login')
def delete(request, id):
    print(id)
    # 해당 객체를 가져와서 삭제
    board = Board.objects.get(id = id)

    # 글 작성자의 id와 접속한 사람의 id가 같을 때
    if board.author.username == request.user.username:
        board.delete()
    # 다를 때
    return HttpResponseRedirect('/board/')

def write_reply(request, id):
    print(request.POST)

    user = request.user
    reply_text = request.POST['replyText']

    # Reply.objects.create(
    #     user = user,
    #     reply_content = reply_text,
    #     board_obj = Board.objects.get(id = id)
    # )

    # queryset 이용
    board = Board.objects.get(id=id)
    board.reply_set.create(
        reply_content = reply_text,
        user = user
    )

    return HttpResponseRedirect('/board/'+ str(id))

def delete_reply(request, id, rid):
    print(f'id:{id} rid:{rid}')

    Board.objects.get(id=id).reply_set.get(id=rid).delete()
    # Reply.objects.get(id = rid).delete() 위에 코드랑 같은 내용

    # return HttpResponseRedirect('/board/'+ str(id))
    return JsonResponse({"result" : "박승인"})

def update_reply(request, id):

    # if request.method == 'GET':
    #     rid = request.GET['rid']

    #     board = Board.objects.get(id = id)

    #     context = {
    #         'update':'update',
    #         'board':board,  #id에 해당하는 Board객체
    #         'reply': board.reply_set.get(id = rid)  # rid에 해당하는 Reply객체
    #     }

    #     return JsonResponse({"reply":context})

    # else :
    rid = request.POST['rid']
    print('여기',rid)
    reply = Board.objects.get(id = id).reply_set.get(id = rid)
    # 폼에 들어있던 새로운 댓글로 수정
    reply.reply_content = request.POST['replyText']
    reply.save()

    return JsonResponse('/board/'+ str(id),safe=False)

def call_ajax(request):
    print('성공?')
    print(request.POST)

    # JSON.stringify 하면 아래 표현 사용 불가
    # print(request.POST['txt'])

    data = loads(request.body)
    print('템플릿에서 보낸 데이터',data)
    print(data['txt'])
    print(type(data))
    return JsonResponse({'result': 'ㅊㅋ'})

def load_reply(request):
    print(request.POST['id'])
    id = request.POST['id']

    # 방법 1
    # reply_list = Reply.objects.filter(board = id)

    # 방법2
    reply_list = Board.objects.get(id=id).reply_set.all()

    # queryset 자체로는 js에서 알 수 없는 타입이여서 json타입으로
    serialized_list = serializers.serialize('json', reply_list)
    return JsonResponse({'response': serialized_list })

myboard/templates/board/board_form.html
{# common/base.html을 상속받겠음 #}
{% extends 'common/base.html' %}
{% block title %}[글쓰기]{% endblock title%}

{% block body %}
<h1>글쓰기</h1>
<!-- 상위 디렉토리로 이동한 후에 write/ 호출 -->
<form action="{% url 'board:write' %}" method="post">
  {% csrf_token %}
  
  <table>
    <tr>
      <th>제목</th>
      <td><input type="text" name="title" /></td>
    </tr>

    <!-- 세션에 writer가 없으면 해당 tr 표시 -->
    <!-- writer가 있으면 해당 tr 표시 안됨 -->
    <!-- {% if not request.session.writer %}
    <tr>
      <th>글쓴이</th>
      <td><input type="text" name="writer" /></td>
    </tr>
    {% endif %} -->

    <tr>
      <th>내용</th>
      <td><textarea name="content" cols="30" rows="10"></textarea></td>
    </tr>
    <tr>
      <th colspan="2">
        <input type="submit" value="글쓰기" />
      </th>
    </tr>
  </table>
</form>
{% endblock body %}

myboard/templates/board/board_update.html
{# common/base.html을 상속받겠음 #}
{% extends 'common/base.html' %}
{% block title %}[글 수정하기]{% endblock title%}

{% block body %}
<h1>글 수정하기</h1>

<form action="{% url 'board:update' board.id %}" method="post">
  {% csrf_token %}
  <table>
    <tr>
      <th>제목</th>
      <td><input type="text" name="title" value="{{ board.title }}" /></td>
    </tr>
    <!-- <tr>
      <th>글쓴이</th>
      <td>
        <input type="text" name="writer" value="{{ board.writer }}" />
      </td>
    </tr> -->
    <tr>
      <th>내용</th>
      <td>
        <textarea name="content" cols="30" rows="10">
        {{ board.content }}</textarea
        >
      </td>
    </tr>
    <tr>
      <th colspan="2">
        <input type="submit" value="수정하기" />
      </th>
    </tr>
  </table>
</form>
{% endblock body %}

myboard/templates/board/index.html
{# common/base.html을 상속받겠음 #}
{% extends 'common/base.html' %}
{% block title %}[게시판]{% endblock title%}
{% block body %}
<script>
  $(document).ready(function(){
    // alert('ㅎㅇ');
  }); 
  
  function callFunction(){
    let data = { 'txt': 'hello' };
    // ajax로 서버와 통신을 할 때에도 csrf토큰은 있어야 한다
    $.ajax({
      url: '/board/callAjax/',
      type: 'post',
      headers: {'X-CSRFTOKEN': '{{ csrf_token }}'},
      data: JSON.stringify(data), // js객체를 문자열화
      success: function(res){
        console.log(res);
        console.log(res.result); // res 객체에 들어있는 result 필드
        console.log('성공');
      }
    });
  }
</script>  
<h1>게시판</h1>
  {% if user.is_authenticated %}
    <a href="{% url 'board:write' %}">글쓰기</a>
  {% endif %}
  {% if page_obj %}
  <input type="button" value="눌러보세요" onclick="callFunction();">
  <div id="result"></div>
  <table border="1">
    <tr>
      <th>번호</th>
      <th>제목</th>
      <th>글쓴이</th>
      <th>작성일</th>
      <th>조회수</th>
    </tr>
    {% for board in page_obj %}
    <tr>
      <td>{{ board.id }}</td>
      <td>
        <!-- 파라미터가 있는 주소를 호출할 때 -->
        <!-- name뒤에 한 칸 띄우고 파라미터 값 지정 -->
        <a href="{% url 'board:detail' board.id %}">{{ board.title }}</a>
      </td>
      <td>{{ board.author }} {{ board.author_id }} {{ board.author.username }}</td>
      <td>{{ board.input_date }}</td>
      <td>{{ board.view_count }}</td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>게시글이 존재하지 않습니다.</p>
  {% endif %}
  <!-- 검색하기 -->
  <!-- action을 비워놓게 되면 현재 페이지의 주소를 다시 호출한다 -->
  <form action="">
    <select name="searchType">
      {% if searchType == 'title' %}
      <!-- option selected속성: 초기 선택 지정  -->
      <option value="title" selected="selected">제목</option>
      {% else %}
      <option value="title">제목</option>
      {% endif %} 
      {% if searchType == 'writer' %}
      <option value="writer" selected="selected">글쓴이</option>
      {% else %}
      <option value="writer">글쓴이</option>
      {% endif %} 
      {% if searchType == 'content' %}
      <option value="content" selected="selected">내용</option>
      {% else %}
      <option value="content">내용</option>
      {% endif %}
    </select>
    <input type="text" name="searchWord" value="{{ searchWord}}" />
    <input type="submit" value="검색" />
  </form>
  <!-- 페이징 -->
  {% if page_obj.has_previous %}
  <a href="?page=1">&laquo;처음 페이지로</a>
  <a href="?page={{ page_obj.previous_page_number }}">이전 페이지로</a>
  {% endif %}

  <!-- paginator의 number 현재 페이지 번호 -->
  <!-- num_pages는 전체 페이지 수 -->
  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">다음 페이지로</a>
  <a href="?page={{ page_obj.paginator.num_pages}}">마지막 페이지로</a>
  {% endif %}
  <br />

  <!-- 페이징2 : 가지고 있는 페이지의 번호 다 보여주기 -->
  {% for page_number in page_obj.paginator.page_range %}
  <a href="?page={{ page_number }}">{{ page_number }}</a> &nbsp; {% endfor %}
  <br />

  <!-- 페이징3: 2 개선한 버전 -->
  {% for page_number in page_obj.paginator.page_range %} 
  {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
    {% if searchWord %}
      <a href='?page={{ page_number }}&searchType={{ searchType }}&searchWord={{ searchWord }}'>{{ page_number }}</a>
    {% else %}
      {% if page_number == page_obj.number %}
        <a href="?page={{ page_number }}" class="color">{{ page_number }}</a>
      {% else %}
        <a href="?page={{ page_number }}">{{ page_number }}</a>
      {% endif %}
    {% endif %}
  {% endif %} 
  {% endfor %}
{% endblock body%}

myboard/templates/board/read.html
{# common/base.html을 상속받겠음 #}
{% extends 'common/base.html' %}
{% block title %}[게시판]{% endblock title%}
{% block body %}
  <script>
    function showUpdateForm(param) {
      // .../board/0/update_reply?rid=0
      location.href = 'update_reply?rid=' + param;
    }

    $(document).ready(function () {
      // console.log('여기는 read');
      $('#btnupdate').hide();
      loadReplyList();
    });

    function writeAjax() {
      let replyText = $('#replyText').val();
      $.ajax({
        url: 'write_reply/',
        type: 'post',
        headers: {
          'X-CSRFTOKEN': '{{ csrf_token }}'
        },
        data: {
          'replyText': replyText
        },
        success: function () {
          loadReplyList();
          $('#replyText').val('');
        }
      });
    }

    function update_ajax(rid, reply) {
      console.log(reply);
      tmp_rid = '#updateReply' + rid
      tmp_bnt1 = '#updateReplybtn' + rid
      tmp_bnt2 = '#cancelReplybtn' + rid
      $(tmp_rid).show();
      $(tmp_rid).val(reply);
      $(tmp_bnt1).show();
      $(tmp_bnt2).show();

    }

    function cancelRepl(rid) {
      tmp_rid = '#updateReply' + rid
      tmp_bnt1 = '#updateReplybtn' + rid
      tmp_bnt2 = '#cancelReplybtn' + rid
      $(tmp_rid).val();
      $(tmp_rid).hide();
      $(tmp_bnt1).hide();
      $(tmp_bnt2).hide();

    }

    function updateRepl(rid, reply) {
      replValue = $('#updateReply' + rid).val()
      $.ajax({
        url: 'update_reply/',
        type: 'post',
        headers: {
          'X-CSRFTOKEN': '{{ csrf_token }}'
        },
        data: {
          'rid': rid,
          'replyText': replValue
        },
        success: function () {
          loadReplyList();
        }
      });
    }

    function updateAjax() {
      let rid = $('#updateRid').val();
      let replyText = $('#replyText').val();
      $.ajax({
        url: 'update_reply/',
        type: 'post',
        headers: {
          'X-CSRFTOKEN': '{{ csrf_token }}'
        },
        data: {
          'rid': rid,
          'replyText': replyText
        },
        success: function () {
          $('#replyText').val('');
          $('#btnwrite').show();
          $('#btnupdate').hide();
          loadReplyList();
        }
      });
    }

    function delete_ajax(param) {
      let id = '{{board.id}}'
      console.log(id);
      let rid = param
      console.log(rid);
      $.ajax({
        url: 'delete_reply/' + param + '/',
        type: 'post',
        headers: {
          'X-CSRFTOKEN': '{{ csrf_token }}'
        },
        success: function (result) {
          $('#replyText').val('');
          $('#btnwrite').show();
          $('#btnupdate').hide();
          loadReplyList();
        }
      });
    }

    function loadReplyList() {
      // console.log('여기는 loadReplyList')
      let bNum = '{{ board.id }}';
      console.log(bNum);
      $.ajax({
        url: '/board/load_reply/',
        type: 'post',
        headers: {
          'X-CSRFTOKEN': '{{ csrf_token }}'
        },
        data: {
          'id': bNum
        },
        success: function (response) {
          // console.log(response);
          console.log(JSON.parse(response['response']));

          let replyList = JSON.parse(response['response']);

          let str = '';
          $.each(replyList, function (i, item) {
            let replyContent = item.fields.reply_content;
            let replyUser = item.fields.user.username;
            // 바로 화면에 붙이려면 append
            // $('#replyList').append(replyContent + '<br>');

            str += replyContent;
            str += " <input type='button' id='" + item.pk + "' value='댓글 수정' onclick='javascript:update_ajax(" + item.pk + ", \"" + replyContent + "\")'>";
            str += " <input type='button' value='댓글 삭제' onclick='javascript:delete_ajax(\"" + item.pk + "\")'>";
            str += '<br>';
            str += " <textarea id=updateReply" + item.pk + " hidden></textarea>";
            str += " <button id=updateReplybtn" + item.pk + " value='완료' onclick='javascript:updateRepl(" + item.pk + ", \"" + replyContent + "\")' hidden>수정 완료</button> ";
            str += " <button id=cancelReplybtn" + item.pk + " value='취소' onclick='javascript:cancelRepl(\"" + item.pk + "\")' hidden>수정 취소</button> ";
            str += '<br>';
            str += '<br>';

          })
          // html을 만들어서 한 번에 넣으려면 html
          $('#replyList').html(str);

        }
      });
    }
  </script>
  <h1>글 보기</h1>
  <table>
    <tr>
      <th>{{ board.id }}</th>
      <th>{{ board.title }}</th>
      <td>{{ board.view_count }}</td>
    </tr>
    <tr>
      <td colspan="2">{{ board.input_date|date:'y.m.d H:i' }}</td>
      <td>{{ board.writer }}</td>
    </tr>
    <tr>
      <td colspan="4">{{ board.content }}</td>
    </tr>
  </table>
  <!-- 수정/삭제 -->
  <!-- username끼리 비교 -->
  {% if board.author.username == user.username %}
    <a href="{% url 'board:update' board.id %}">글수정</a>
    /
    <a href="{% url 'board:delete' board.id %}">글삭제</a>
  {% endif %}
  <!-- board.author 는 user하고 비교ㅏ -->
  <div id="replyArea">
    <!-- 댓글 목록 표시 -->
    <div id="replyList">
      <!-- board객체 뿐 아니라 board와 fk로 엮인 객체는 -->
      <!-- board.모델이름_set으로 가져올 수 있다 -->
      <!-- {% if board.reply_set %} {% for reply in board.reply_set.all %} {{ reply }}&nbsp;&nbsp;&nbsp; <a href="#" onclick="showUpdateForm('{{reply.id}}')">수정</a>/ <a href="{% url 'board:delete_reply' id=board.id rid=reply.id %}">삭제</a> <br> {% endfor %} {% else %} <p>등록된 댓글이 없습니다</p> {% endif %} -->
      <br>
      <br>

    </div>
    <!-- 댓글 입력 폼-->
    <div id="replyForm">
      <textarea id="replyText"></textarea>
      <input type="button" value="댓글쓰기" id='btnwrite' onclick='writeAjax()'>
      <input type="button" value="댓글수정" id='btnupdate' onclick='updateAjax()'>
      <input type="hidden" id='updateRid'>
    </div>
  </div>

  <form action="{% url 'board:index' %}">
    <input type="submit" value="목록으로"/>
  </form>
{% endblock body %}